### PR TITLE
fix(renderwindowinteractor): return first interactive renderer viewpo…

### LINKED ISSUE #1487: Overlay ViewPort Interaction
Hello, I have a scene with 2 viewports:
ezgif com-video-to-gif (7)

However I'd like to be able to interact only with the upper left viewport when the mouse is on it.
Is it possible?

If needed, the link for the synchronizable scene is here :
https://drive.google.com/file/d/1SgWOJBR6qYVlU6AujDxPE3ZyVMIYqicF/view?usp=sharing

### PR DESCRIPTION
**Pull request by xavArtley**
…rt found as pokedRenderer

Fix the problem when multiple viewports overlay one over the other. The actual behavior iterate over
all renderer and return the last one instead the first one

fix #1487

### CODE REVIEW

**Comment by jourdain** [comment]
We need to keep the renderer that is on the top [layer](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Core/Renderer/index.js#L654). 
You can not assume anything in term of ordering. So you need to check that layer to only keep the top one.

**Comment by jourdain** [comment]
Or sort it.

File: Sources/Rendering/Core/RenderWindowInteractor/index.js [hunk 1]
```diff
@@ -668,7 +668,14 @@ function vtkRenderWindowInteractor(publicAPI, model) {
     if (!model.view) {
       return null;
     }
-    const rc = model.view.getRenderable().getRenderersByReference();
+    const rc = model.view
+      .getRenderable()
+      .getRenderersByReference()
+      .sort((a, b) => {
```
Comment (jourdain) [inline Sources/Rendering/Core/RenderWindowInteractor/index.js:674]:
```
const rc = model.view.getRenderable().getRenderersByReference();
rc.sort((a, b) => a.getLayer() - b.getLayer());
```

@martinken is it ok to sort that array in place?

**Comment by jourdain** [comment]
LGTM, thanks @xavArtley !
If it is working for you, I'll merge it.

**Comment by xavArtley** [comment]
> 
> 
> LGTM, thanks @xavArtley !
> If it is working for you, I'll merge it.

it's ok for me thx.
