### PR TITLE
Picking translucent

### LINKED ISSUE #2800: [Bug] HardwareSelector incorrect attributeID/propID with opacity < 1
### High-level description

Picking using HardwareSelector in the presence of opacity can return incorrect attributeID and propID, which can correspond to the furthest away face/object. A hack is proposed in the forum post linked below, where opacity is set to 1 before the `hardwareSelector.getSourceDataAsync` call, and then reset immediately after

### Steps to reproduce

https://jsfiddle.net/rmart/g8jxwkdz/1/ to reproduce, 

https://jsfiddle.net/rmart/g8jxwkdz/12/ implements the "hack"

### Detailed Current Behavior

Logged here https://discourse.vtk.org/t/hardware-selector-with-transparency-returning-wrong-attribute-id-prop-id/11270

> Hello, I am looking for some help to make hardware selector return correct attributeID and propID in the presence of opacity.
>
> Very basically, I am trying to select faces of a polydata using the hardware selector, but am finding that when actors have opacity < 1, the attributeID and propID returned (often, but not always) refer to the furthest away objects instead of the one I am clicking on (i.e., my pick appears to go through to the other side… as if the order was reversed…). This applies to faces in a single object (i.e., I pick faces on the other side of the transparent object), as well as when making a pick when another transparent object is behind (faces from the other object are selected). The really odd thing is that the xyz position is correct, its just the attributeID and propID that point to the wrong thing.
>
> The behavior is demonstrated in this screengrab, and in the js-fiddle that follows:
>
> picking-hw-opacity
> https://jsfiddle.net/rmart/g8jxwkdz/1/
>
>  am wondering if there is something clearly wrong being done in this example? Most of the logic is borrowed from the Hardware Selector example on the vtk-js docs.
>
> Thanks in advance!

Using the hack in a renderWindow with lots of complex actors, with transparency, results in the HardwareSelector picking the right objects and getting the right attribute ID's and is much more performant than falling back on the raycast-pickers.

### Environment

- vtk.js version: latest, https://unpkg.com/vtk.js@27.3.0/vtk.js
- Browsers: Chrome, firefox
- OS: macos, windows, linux

### PR DESCRIPTION
**Pull request by sankhesh**
PropID of the last rendered prop was returned by the hardware selector when picking translucent actors overlaid on each other.
### Context

fix #2800 
### Results

Corrent prop ids being returned.
### Changes

- [x] Documentation and TypeScript definitions were updated to match those changes

### PR and Code Checklist

- [x] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [x] Run `npm run reformat` to have correctly formatted code

### Testing

- [x] This change adds or fixes unit tests 
- [x] Tested environment:
  - **vtk.js**: master
  - **OS**: Windows 11
  - **Browser**: Chrome

### CODE REVIEW

File: Sources/Rendering/OpenGL/Actor/index.js [hunk 1]
```diff
@@ -152,7 +152,10 @@ function vtkOpenGLActor(publicAPI, model) {
   // Renders myself
   publicAPI.translucentPass = (prepass, renderPass) => {
     if (prepass) {
-      model.context.depthMask(false);
+      model.context.depthMask(
+        model._openGLRenderer.getSelector() &&
```
Comment (bruyeret) [inline Sources/Rendering/OpenGL/Actor/index.js:156]: We may want a configurable threshold on opacity, that enables picking for translucent actors
For example, we don't want to pick when the opacity is 0
This threshold can be ignored here as we want to completely disable rendering of translucent actors if they don't reach the threshold (if we only disable depth mask, the actors will be rendered anyway), so the threshold test could be when doing the actual rendering

File: package-lock.json
Comment (daker) [inline package-lock.json:1]: Please remove the package-lock.json changes

**Review by daker — CHANGES_REQUESTED** [review]

**Review by bruyeret — COMMENTED** [review]
The CI has caught the `test.only` usage that should be removed
Thanks for adding this feature and a test case 👍

File: package-lock.json
Comment (bruyeret) [reply package-lock.json:1]: It was intentional, and has been done in a separate commit:
> `chore(package-lock): fixed node package issues with npm audit fix`
Why is it bad?

File: Sources/Rendering/OpenGL/Actor/index.js (hunk 1 above)
Comment (sankhesh) [reply Sources/Rendering/OpenGL/Actor/index.js:156]: @bruyeret Sorry for not getting back to you sooner. We don't need a configurable opacity threshold for picking simply because if the actor's opacity is 0, it will not be rendered (even for selection). If users desire to ignore certain actors from selection, that can be done via `PickableOff`. WDYT?

File: package-lock.json
Comment (sankhesh) [reply package-lock.json:1]: @daker I removed the package-lock changes and will move them to a separate PR.

File: Sources/Rendering/OpenGL/Actor/index.js (hunk 1 above)
Comment (bruyeret) [reply Sources/Rendering/OpenGL/Actor/index.js:156]: Yes that's ok, it works 👍

**Review by bruyeret — APPROVED** [review]
