### PR TITLE
fix(AbstractMapper3D): Fix usage and implementation of getCenter

### LINKED ISSUE #1123: Picker: get wrong center in intersectWithLine
I am trying to use the `vtkPicker` and get the picked actors. In the `intersectWithLine` function, I have an issue with the `center` which is alway an empty array: https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Core/Picker/index.js#L44

It seems to work by changing this line to
```
    const center = mapper.getCenter();
```
But there is maybe a bug somewhere, maybe in `getCenter`...?
Why to you splice the `model.center` instead of always returning it?

### PR DESCRIPTION
**Pull request by floryst**
Fixes #1123 @BotellaA

### CODE REVIEW

File: Sources/Rendering/Core/AbstractMapper3D/index.js [hunk 1]
```diff
@@ -16,14 +16,11 @@ function vtkAbstractMapper3D(publicAPI, model) {
...
-  publicAPI.getCenter = (...center) => {
+  publicAPI.getCenter = () => {
     publicAPI.getBounds();
     for (let i = 0; i < 3; i++) {
       model.center[i] = (model.bounds[2 * i + 1] + model.bounds[2 * i]) / 2.0;
     }
-    if (Array.isArray(center[0])) {
-      center[0] = model.center.splice(0);
-    }
     return model.center;
```
Comment (finetjul) [inline Sources/Rendering/Core/AbstractMapper3D/index.js]: To be consistent with getArray in macro.js, shouldn't we return a copy of the center ([].concat(model.center)). I'm afraid it could be error prone to return a reference and some developer ends up modifying it.

File: Sources/Rendering/Core/AbstractMapper3D/index.js [hunk 2]
```diff
@@ -16,14 +16,11 @@ function vtkAbstractMapper3D(publicAPI, model) {
     }
   };
 
-  publicAPI.getCenter = (...center) => {
+  publicAPI.getCenter = () => {
```
Comment (finetjul) [inline Sources/Rendering/Core/AbstractMapper3D/index.js]: This changes the API. 
It probably shouldn't have just be a patch version release. Let's hope that no-one used the getCenter(center) API externally to VTK.JS :-)

File: Sources/Rendering/Core/AbstractMapper3D/index.js (hunk 1 above)
Comment (floryst) [reply Sources/Rendering/Core/AbstractMapper3D/index.js]: Yes you are right. :P I will make that change.

File: Sources/Rendering/Core/AbstractMapper3D/index.js (hunk 2 above)
Comment (floryst) [reply Sources/Rendering/Core/AbstractMapper3D/index.js]: Indeed. However, anyone using `getCenter(center)` would have incorrect code anyways, since `getCenter(center)` doesn't actually do anything. (`center` doesn't actually change.)
