### PR TITLE
fix(ColorTransferFunction): misuse of return value

### LINKED ISSUE #2881: [Bug] Error in ColorTransferFunction when indexed Lookup Mode is used
### Bug description

In getColor() function   there is a call to getNodeValue function where returned value is passed by function argument (array). 
https://github.com/Kitware/vtk-js/blob/188c7fb379a87b97f39262659d4a66aedc2e88d3/Sources/Rendering/Core/ColorTransferFunction/index.js#L395-L398

But getNodeValue is setting 6-element array instead of object with r,g,b properties as above.
https://github.com/Kitware/vtk-js/blob/188c7fb379a87b97f39262659d4a66aedc2e88d3/Sources/Rendering/Core/ColorTransferFunction/index.js#L962-L976

So the code in getColor should be:
```
 rgb[0] = nodeVal[1];
 rgb[1] = nodeVal[2];
 rgb[2] = nodeVal[3];
```

### Steps to reproduce

Any use of `ColorTransferFunction` with `setIndexedLookup(true)`

### Detailed Behavior

_No response_

### Expected Behavior

The getColor function should return color indiced by annotation, instead undefined values are returned.

### Environment

- vtk.js version: 17.17.x
- Browsers: any
- OS: any

### PR DESCRIPTION
**Pull request by floryst**
### Context

Fixes #2881 
- getNanColor returns an array and accepts no parameters.
- getNodeValue sets nodeVal to an array, not object.

### Results

- Correct usage of getNanColor and getNodeValue

### Changes

- [x] Updates to vtkColorTransferFunction

### PR and Code Checklist

- [x] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [x] Run `npm run reformat` to have correctly formatted code

### Testing

- [ ] This change adds or fixes unit tests

### CODE REVIEW

File: Sources/Rendering/Core/ColorTransferFunction/index.js [hunk 1]
```diff
@@ -1030,7 +1033,10 @@ function vtkColorTransferFunction(publicAPI, model) {
       rgba[3] = 1.0; // NodeColor is RGB-only.
       return;
     }
-    publicAPI.getNanColor(rgba);
+    const nanColor = publicAPI.getNanColor();
```
Comment (jourdain) [inline Sources/Rendering/Core/ColorTransferFunction/index.js:1036]: does that call do a new allocation? Maybe use getNanColorAsReference() if available instead?

File: Sources/Rendering/Core/ColorTransferFunction/index.js [hunk 2]
```diff
@@ -389,13 +389,16 @@ function vtkColorTransferFunction(publicAPI, model) {
...
+        rgb[0] = nanColor[0];
+        rgb[1] = nanColor[1];
+        rgb[2] = nanColor[2];
       } else {
         const nodeVal = [];
         publicAPI.getNodeValue(idx % numNodes, nodeVal);
-        rgb[0] = nodeVal.r;
-        rgb[1] = nodeVal.g;
-        rgb[2] = nodeVal.b;
+        rgb[0] = nodeVal[1];
```
[the remark this answers is not in the document]
Comment (floryst) [reply Sources/Rendering/Core/ColorTransferFunction/index.js:399]: Yep. I can add a comment indicating such.

File: Sources/Rendering/Core/ColorTransferFunction/index.js (hunk 1 above)
Comment (floryst) [reply Sources/Rendering/Core/ColorTransferFunction/index.js:1036]: Ah good point. Yes, I think there's a copy here. I forgot about the AsReference methods.

**Review by jourdain — APPROVED** [review]

File: Sources/Rendering/Core/ColorTransferFunction/index.js [hunk 3]
```diff
@@ -389,13 +389,17 @@ function vtkColorTransferFunction(publicAPI, model) {
       // todo
       const idx = publicAPI.getAnnotatedValueIndexInternal(x);
       if (idx < 0 || numNodes === 0) {
-        publicAPI.getNanColor(rgb);
```
Comment (finetjul) [inline Sources/Rendering/Core/ColorTransferFunction/index.js:392]: It would be a convenient signature to also support in `macros.js!getArray()` function

Comment (floryst) [reply Sources/Rendering/Core/ColorTransferFunction/index.js:392]: I certainly think it's a good way to write an array type directly into a destination array. It'll involve rewriting a lot of typescript definitions to include the optional out param...
