### PR TITLE
docs(ts): fix typescript definitions

### LINKED ISSUE #466: Typescript type definitions
Are typescript type definitions planned for vtk.js? (as per available packages for [three.js](https://threejs.org/), for example https://www.npmjs.com/package/@types/three)

### PR DESCRIPTION
**Pull request by daker**
This should fix the `vtkMatrixBuilder` and `setData` definitions

fix #466

### CODE REVIEW

File: Sources/macro.d.ts [hunk 1]
```diff
@@ -56,6 +56,18 @@ export enum TYPED_ARRAYS {
   Int32Array,
 }
 
+export type TypedArray =
+    | number[]
```
Comment (finetjul) [inline Sources/macro.d.ts:60]: @daker any reason why `number[]` is part of `TypedArray` ?

Comment (daker) [reply Sources/macro.d.ts:60]: i think you are right, it should not be part of it
