### PR TITLE
fix(links): clear Cells and Links arrays when polydata is cleared

### LINKED ISSUE #3361: [Bug] ContourLoopExtraction doesn't work anymore
### Bug description

Open https://kitware.github.io/vtk-js/examples/ContourLoopExtraction/index.html
Use the example

```javascript
Uncaught TypeError: Cannot read properties of null (reading 'forEach')
    at e.buildLinks (ContourLoopExtraction.js:1:175374)
    at e.buildLinks (ContourLoopExtraction.js:1:204265)
    at DT (ContourLoopExtraction.js:1:712029)
```

### Steps to reproduce

Check description

### Detailed Behavior

Check description

### Expected Behavior

Example should work as expected

### Environment

- vtk.js version:
- Browsers:
- OS:

### PR DESCRIPTION
**Pull request by finetjul**
BuildLinks enforces building cells only if they do not exist. When clearing the polydata, cells and links must be cleared accordingly. Same when verts, lines, polys and strips arrays are changed

fix #3361

### Context
Filters reuse their previous output data, but they now clear them.
A crash was happening when trying to access a cell that does not exist in model.cells.
This is because the model.cells array is outdated.

### Results
Enforce the cells array to be recomputed after clearing a polydata.
The ContourLoopExtraction example now works again.

### Changes
- [ ] Documentation and TypeScript definitions were updated to match those changes

### PR and Code Checklist
- [x] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [x] Run `npm run reformat` to have correctly formatted code

### Testing
- [x] This change adds or fixes an example
- [x] Tested environment:
  - **vtk.js**: master
  - **OS**: Windows 11
  - **Browser**: Chrome

### CODE REVIEW

File: Sources/Common/DataModel/PolyData/index.js [hunk 1]
```diff
@@ -180,7 +187,7 @@ function vtkPolyData(publicAPI, model) {
    * topologically complex queries.
    */
   publicAPI.buildLinks = (initialSize = 0) => {
-    if (model.cells === undefined) {
+    if (model.cells == null) {
```
Comment (daker) [inline Sources/Common/DataModel/PolyData/index.js:190]: I did test the code with ContourLoopExtraction example it only works with `model.cells === undefined` and not `model.cells == null`

Comment (daker) [reply Sources/Common/DataModel/PolyData/index.js:190]: nvm i think it was a refresh issue on my side, it works

**Review by daker — APPROVED** [review]
LGTM
