### PR TITLE
fix(IFCImporter): fix normals

### LINKED ISSUE #3189: [Bug] Wrong normals in IFC ?
### Bug description

Depending on the camera position, the IFC scene example gets all black

image
image

### Steps to reproduce

open the [IFC example](https://kitware.github.io/vtk-js/examples/IFCImporter.html) and rotate the camera

### Detailed Behavior

Maybe there is a problem with the normals ? the lights ?
Alternatively, should the scene example file be revised and add more "ambient" light ?

### Expected Behavior

I would expect a more lit scene

### Environment

- vtk.js version: master
- Browsers: Chrome
- OS: Windows

### PR DESCRIPTION
**Pull request by daker**
### Context
fix #3189

### Results

https://github.com/user-attachments/assets/6db63ed2-ff76-4a48-862b-fa9c4d173bd5

### Changes

- [x] Documentation and TypeScript definitions were updated to match those changes

### PR and Code Checklist

- [x] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [x] Run `npm run reformat` to have correctly formatted code

### Testing

- [ ] This change adds or fixes unit tests 
- [x] Tested environment:
  - **vtk.js**: 
  - **OS**: 
  - **Browser**:

### CODE REVIEW

File: Sources/IO/Geometry/IFCImporter/index.js [hunk 1]
```diff
@@ -244,32 +245,40 @@ function vtkIFCImporter(publicAPI, model) {
...
-      let apd = vtkAppendPolyData.newInstance();
+      const oapd = vtkAppendPolyData.newInstance();
 
       opaqueMeshes.forEach((mesh) => {
         const pd = createColoredPolyDataFromIFCMesh(mesh);
-        apd.addInputData(pd);
+        oapd.addInputData(pd);
       });
 
+      const opdn = vtkPolyDataNormals.newInstance();
```
Comment (finetjul) [inline Sources/IO/Geometry/IFCImporter/index.js:255]: is this overwritting existing normals ? If so, it might not be ideal. 
vtkPolyDataNormals does not perform well in case of sharp edges.

Comment (daker) [reply Sources/IO/Geometry/IFCImporter/index.js:255]: this is only for "merged geometries" which create two actors one to group opaque meshes and one transparent to group transparent meshes, the default option will create actors with their correct normals.

Comment (finetjul) [reply Sources/IO/Geometry/IFCImporter/index.js:255]: Would you say that the AppendPolyData is "dropping" the normals of the input polydatas ?

Comment (daker) [reply Sources/IO/Geometry/IFCImporter/index.js:255]: By looking at the code, it doesn't seems to be the case

Comment (finetjul) [reply Sources/IO/Geometry/IFCImporter/index.js:255]: vtkAppendPolyData seems to preserve normals if they exist in ALL the input polydatas.

So why do you need to recompute normals here ? Is is because some polydata are missing normals ?

Comment (daker) [reply Sources/IO/Geometry/IFCImporter/index.js]: i think it should be fixed

File: Sources/IO/Geometry/IFCImporter/index.js [hunk 2]
```diff
@@ -94,11 +94,34 @@ function vtkIFCImporter(publicAPI, model) {
...
+        userMatrix[10],
+        0,
+        0,
+        0,
+        0,
+        1,
+      ];
+      const rotationMatrix = vtkMatrixBuilder
+        .buildFromRadian()
+        .setMatrix(rotMatrix);
```
Comment (finetjul) [inline Sources/IO/Geometry/IFCImporter/index.js:117]: Could the following work ?
`const rotationMatrix = vtkMatrixBuilder.buildFromRadian().multiply3x3(mat3.fromMat4(userMatrix))`

Comment (daker) [reply Sources/IO/Geometry/IFCImporter/index.js]: It works with a small adjustment

**Review by finetjul — APPROVED** [review]
LGTM
