### PR TITLE
fix(arrowhandlerepresentation): fix crash in ArrowHandleRepresentation

### LINKED ISSUE #2416: LineWidget Example Broken
### High-level description
LineWidget Example throws error when attempting to add widget.

### Steps to reproduce

- Run the [LineWidget example](https://kitware.github.io/vtk-js/examples/LineWidget.html)
- Click on "Add Widget"

### Detailed behavior
Attempting to add the widget sends the following error to the console:
```
LineWidget.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'isVisible')
    at Object.e.updateActorVisibility (LineWidget.js:1:646605)
    at Object.UO.e.updateHandleVisibility (LineWidget.js:1:667871)
    at aA (LineWidget.js:1:674833)
    at HTMLButtonElement.<anonymous> (LineWidget.js:1:678231)
```
The widget is not displayed.

### Expected behavior
It should insert a LineWidget and not generate the error.

### Environment
- **vtk.js**: v24.10.0
- **OS**: not relevant
- **Browser**: not relevant

### PR DESCRIPTION
**Pull request by finetjul**
With #2381, getRepresentationStates() can be an empty array, hence a crash when getShape() is called
on a non-existant first element.

fix #2416

### Context
LineWidget example was crashing

### Results
LineWidget is no longer crashing

### Changes
Support when getRepresentationStates() returns an empty array (no origin and visible sub states)

- [ ] Documentation and TypeScript definitions were updated to match those changes

### PR and Code Checklist
- [x] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [x] Run `npm run reformat` to have correctly formatted code

### Testing
- [ ] This change adds or fixes unit tests 
- [x] Tested environment:
  - **vtk.js**: master
  - **OS**: Windows 10
  - **Browser**: Chrome

### CODE REVIEW

File: Sources/Widgets/Representations/ArrowHandleRepresentation/index.js [hunk 1]
```diff
@@ -332,11 +332,11 @@ function vtkArrowHandleRepresentation(publicAPI, model) {
     ctxVisible = true,
     handleVisible = true
   ) => {
-    const state = publicAPI.getRepresentationStates()[0];
+    const hasValidState = publicAPI.getRepresentationStates().length > 0;
     superClass.updateActorVisibility(
       renderingType,
       ctxVisible,
-      handleVisible && state.isVisible()
+      handleVisible && hasValidState
```
Comment (floryst) [inline Sources/Widgets/Representations/ArrowHandleRepresentation/index.js:339]: Just to check: we only care if there are available states, and not that the first state (if it exists) is visible, correct?

**Review by floryst — APPROVED** [review]
LGTM
