### PR TITLE
WIP Fix #1996 and add debounced function cancellation

### LINKED ISSUE #1996: macro.shouldUpdate doesn't check for deleted output
### High-level description

vtk filters fail to update when the filter output dataset is deleted via `.delete()`.

### Steps to reproduce

- Create a vtkTrivialProducer, which is a 1-1 macro.algo that outputs the input dataset
- set the input to some vtk dataset
- get the filter output, and call `getOutputData().delete()`
- set the input to some new vtk dataset
- `getOutputData()` returns the old deleted dataset

### Detailed behavior

`macro.shouldUpdate` checks if it should update when `output.getMTime()` is stale. However, when `output` is a deleted object, `output.getMTime()` returns undefined and therefore all numerical checks yield false.

### Expected behavior

Even when the output dataset is deleted, filters should still run if their inputs are updated.

### Environment
- **vtk.js**: 18.5.1 and lower

### PR DESCRIPTION
**Pull request by floryst**
### Context

- Fixes #1996 
- Adds support for cancelling debounced calls.

### Changes

- Fixes `macro shouldUpdate()` to check for output dataset deletion status
- Adds support for cancelling debounced calls via `debouncedFunction.cancel()`

### Testing

- [x] Add test for shouldUpdate fix
- [x] verify typescript defs work for vtkDebouncedFunction

### CODE REVIEW

**Comment by floryst** [comment]
@agirault @WillCMcC I will make a react-vtk-js issue to cross-ref the debounce cancel functionality.

File: Sources/macro.js [hunk 1]
```diff
@@ -705,6 +705,11 @@ export function algo(publicAPI, model, numberOfInputs, numberOfOutputs) {
       if (!model.output[count]) {
         return true;
       }
+
+      if (model.output[count].isDeleted()) {
+        return true;
+      }
+
       const mt = model.output[count].getMTime();
       if (mt < localMTime) {
```
Comment (agirault) [inline Sources/macro.js:714]: @floryst ah, we're comparing `MTime` of `output` and of the actual algo, not of the `input`, so that makes sense, since I assume the modified flag will be changed when the input is changed on the algo. I believe that covers the concern I had.

File: Sources/Testing/testAlgorithm.js [hunk 2]
```diff
@@ -63,3 +63,50 @@ test('Macro methods algo tests', (t) => {
 
   t.end();
 });
+
+test('Macro shouldUpdate returns true if output is deleted', (t) => {
```
Comment (agirault) [inline Sources/Testing/testAlgorithm.js:67]: image
