### PR TITLE
fix: use half float flag overrides norm16 flag

### LINKED ISSUE #2681: useHalfFloat should be an independent option due to webgl2 norm16 implementation bug
### High-level description

WebGL2 EXT_NORM_16 has an implementation bug for apple devices which lead to webgl context being lost. See https://bugs.chromium.org/p/chromium/issues/detail?id=1408247. Thus, the useHalfFloat option should be a independent flag from norm_16 support

Changes proposed to the below:
https://github.com/Kitware/vtk-js/blob/b6e2fa6a143d51075ef42701bd137ffa145fd468/Sources/Rendering/OpenGL/Texture/index.js#L1228-L1235
https://github.com/Kitware/vtk-js/blob/b6e2fa6a143d51075ef42701bd137ffa145fd468/Sources/Rendering/OpenGL/Texture/index.js#L457-L467

### PR DESCRIPTION
**Pull request by Ouwen**
### Context

Fixes #2681, `preferSizeOverAccuracy` enables `halfFloat` use which overrides `norm16`

### Results

Safari is able to use half float textures from uint16/int16 array buffers.
image

### Changes

- [x] Documentation and TypeScript definitions were updated to match those changes

### PR and Code Checklist

- [x] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [x] Run `npm run reformat` to have correctly formatted code

### Testing

- [x] Tested environment:
  - **vtk.js**: 
  - **OS**: 
  - **Browser**:

### CODE REVIEW

File: Sources/Rendering/OpenGL/Texture/index.js [hunk 1]
```diff
@@ -1224,15 +1226,14 @@ function vtkOpenGLTexture(publicAPI, model) {
...
-    // if we can use norm16, there is no need to use halfFloat then
-    model.useHalfFloat = model.oglNorm16Ext
-      ? false
-      : checkUseHalfFloat(
-          dataType,
-          computedOffset,
-          computedScale,
-          preferSizeOverAccuracy
-        );
+    // preferSizeOverAccuracy will override norm16 due to bug with norm16 implementaiton
```
Comment (floryst) [inline Sources/Rendering/OpenGL/Texture/index.js:1229]: "implementaiton" -> "implementation"

**Review by floryst — COMMENTED** [review]
@sedghi what do you think?

**Comment by sedghi** [comment]
@floryst I think this is the right approach since the norm16 seems to be buggy for couple of hardwares. We filed bug reports to chromium and Safari and hopefully they fix it

File: Sources/Rendering/OpenGL/Texture/index.js [hunk 2]
```diff
@@ -1379,9 +1382,13 @@ function vtkOpenGLTexture(publicAPI, model) {
...
       }
-      if (model.oglNorm16Ext && dataType === VtkDataTypes.SHORT) {
+      if (
+        model.oglNorm16Ext &&
+        !model.useHalfFloat &&
+        dataType === VtkDataTypes.UNSIGNED_SHORT
+      ) {
         for (let c = 0; c < numComps; ++c) {
-          model.volumeInfo.scale[c] = 32767.0;
+          model.volumeInfo.scale[c] = 65535.0;
```
Comment (Ouwen) [inline Sources/Rendering/OpenGL/Texture/index.js:1391]: I think this scale info was a bug for `unsigned_short`

**Comment by Ouwen** [comment]
@floryst is this okay to merge?

File: Sources/Rendering/OpenGL/Texture/index.js [hunk 3]
```diff
@@ -1392,10 +1399,12 @@ function vtkOpenGLTexture(publicAPI, model) {
...
       }
-      if (model.oglNorm16Ext && dataType === VtkDataTypes.UNSIGNED_SHORT) {
-        for (let c = 0; c < numComps; ++c) {
-          model.volumeInfo.scale[c] = 65535.0;
-        }
+      if (
+        dataType === VtkDataTypes.FLOAT ||
+        (model.useHalfFloat &&
+          (dataType === VtkDataTypes.SHORT ||
+            dataType === VtkDataTypes.UNSIGNED_SHORT))
```
Comment (finetjul) [inline Sources/Rendering/OpenGL/Texture/index.js:1406]: this indentation does not seem to follow the lint rules, did you enable them ?

File: Sources/Rendering/OpenGL/Texture/index.js [hunk 4]
```diff
@@ -1365,11 +1366,13 @@ function vtkOpenGLTexture(publicAPI, model) {
     // WebGL2 path, we have 3d textures etc
     if (model._openGLRenderWindow.getWebgl2()) {
       if (
-        dataType === VtkDataTypes.FLOAT ||
-        (model.useHalfFloat &&
-          (dataType === VtkDataTypes.SHORT ||
-            dataType === VtkDataTypes.UNSIGNED_SHORT))
```
Comment (Ouwen) [inline Sources/Rendering/OpenGL/Texture/index.js:1371]: @finetjul the indent was removed from upstream here. I agree it is a bit strange but seems like it is following the ESLint.

**Comment by Ouwen** [comment]
@finetjul I just rebased to latest master since your last view

**Comment by finetjul** [comment]
LGTM from a purely syntaxis point of view.

File: Sources/Rendering/OpenGL/Texture/index.js (hunk 2 above)
Comment (floryst) [reply Sources/Rendering/OpenGL/Texture/index.js:1391]: This makes sense to me.

**Comment by floryst** [comment]
Overall, LGTM. The method signature docs update is the only thing left.

File: Sources/Rendering/OpenGL/RenderWindow/index.d.ts [hunk 5]
```diff
@@ -270,7 +270,7 @@ export interface vtkOpenGLRenderWindow extends vtkOpenGLRenderWindowBase {
 	 * @param {Number} numComps 
 	 * @param {Boolean} useFloat
```
[the remark this answers is not in the document]
Comment (Ouwen) [reply Sources/Rendering/OpenGL/RenderWindow/index.d.ts:271]: good catch! I've updated the function signature.

**Review by Ouwen — COMMENTED** [review]
@floryst @finetjul ready for review! Many thanks for the help with this PR.

**Review by floryst — APPROVED** [review]
LGTM!
