### PR TITLE
fix(PLYReader): add support for duplicatePointsForFaceTexture

### LINKED ISSUE #2841: [Bug] PLY Reader does not support point clouds (only vertex data with no face data)
### Bug description

Hi VTK team, thanks for your outstanding work over the years. VTK is truly a world-class rendering library!

We are trying to use vtk-js to load a point cloud from a PLY file containing the following header. However, after looking at the PLY reader source code in JS, it seems that this type of file does not have a function to load it as a point cloud - only PLY files containing faces seem to be supported. This functionality works well on the C++/desktop version of VTK where we use it extensively.

We would be happy to write the required JS ourselves in the PLY reader function if you could give us a little bit of guidance as to what is required? Or if there is something we are missing with how to load the PLY file? **Thank you.**

**ply
format binary_little_endian 1.0
comment VTK generated PLY File
obj_info vtkPolyData points and polygons: vtk4.0
element vertex 226352
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
element face 0
property list uchar int vertex_indices
property uchar red
property uchar green
property uchar blue
end_header**

### Steps to reproduce

1. Load a PLY file using C++/desktop VTK that contains only vertex data (no faces). Observe that it loads correctly and displays a point cloud with each point coloured correctly (RGB)

3. Load the same PLY file using the vtk-js "PLYReader" example. Notice that PLY files containing face information load OK, but PLY files without faces (only vertex data) do not load at all.

### Detailed Behavior

_No response_

### Expected Behavior

The PLYReader class correctly loads the vertex data and the point cloud is displayed correctly like it does in the desktop/C++ version of VTK.

### Environment

- vtk.js version: Latest
- Browsers: Google Chrome
- OS: macOS & Windows

### LINKED ISSUE #2877: [Bug] Adding textures with gaps in the PLYReader 28.3.3
### Bug description

Load the ply file with vtkPLYReader and add textures with vtkTexture, but the added textures have gaps.

It is normal to load the same file using meshLab software.

### Steps to reproduce

ply01

const reader = vtkPLYReader.newInstance();
  const mapper = vtkMapper.newInstance({ scalarVisibility: false });
  const actor = vtkActor.newInstance();

  actor.setMapper(mapper);
  mapper.setInputConnection(reader.getOutputPort());

  reader
  .setUrl(lowerFolder)
  .then(async (res) => {
    const fullScreenRenderer = vtkFullScreenRenderWindow.newInstance();
    let renderer = fullScreenRenderer.getRenderer();
    let renderWindow = fullScreenRenderer.getRenderWindow();

    const text = await reader.getDataAccessHelper().fetchText(null,lowerFolder);
    const headText = text.split("end_header")[0];
    const TextureFile0 = headText.split("TextureFile")[1];
    const textureUrl = TextureFile0.split("\n")[0].trim();

    const image = new Image();
    image.src = folder + textureUrl;
    const texture = vtkTexture.newInstance();
    texture.setInterpolate(true);
    texture.setImage(image);
    actor.addTexture(texture);

    renderer.addActor(actor);

    setTimeout(() => {
      renderWindow.render();
      fullScreenRenderer.getInteractor().render();
    }, 200);

    if (renderer && renderWindow) {
      const resetCamera = renderer.resetCamera;
      const render = renderWindow.render;
      resetCamera();
      render();
    }
  })

### Detailed Behavior

_No response_

### Expected Behavior

The PLYReader and  class vtkTexture correctly loads.
If the PLYReader class can automatically read the jpg address in the ply file, it would be perfect

### Environment

- vtk.js version: 28.3.3 & 25.15.2
- Browsers: chrome 114.0.5735.248
- OS: Windows 11

### LINKED ISSUE #3047: The vtkPLYReader parseAsText method reported an error  [Bug]
### Bug description

The vtkPLYReader parseAsText method reported an error when passing in the PLY file text

### Steps to reproduce

1. Read the PLY file using the readAsText method in new FileReader();
2. vtkPLYReader parseAsText receives Text error
Snipaste_2024-03-27_17-40-37

### Detailed Behavior

_No response_

### Expected Behavior

VtkPLYReader parseAsText can read readAsText data normally

### Environment

- vtk.js version: 30.2.0
- Browsers: chrome
- OS: windows

### PR DESCRIPTION
**Pull request by daker**
### Context
fixes #2841
fixes #2877
fixes #3047

### Results

| Before | After |
| -------- | ------- |
| image| image    |

| Before | After |
| -------- | ------- |
| image | image   |

### Changes

- [x] Documentation and TypeScript definitions were updated to match those changes

### PR and Code Checklist

- [x] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [x] Run `npm run reformat` to have correctly formatted code

### Testing

- [x] This change adds or fixes unit tests 
- [x] Tested environment:
  - **vtk.js**: 
  - **OS**: 
  - **Browser**:

### CODE REVIEW

File: Sources/IO/Geometry/PLYReader/index.d.ts [hunk 1]
```diff
@@ -13,7 +13,17 @@ interface IPLYReaderOptions {
 /**
  *
  */
-export interface IPLYReaderInitialValues {}
+export interface IPLYReaderInitialValues {
+  /**
+   * Controls whether points are duplicated for face-texture mapping.
```
Comment (finetjul) [inline Sources/IO/Geometry/PLYReader/index.d.ts:18]: mention that it is true by default

File: Sources/IO/Geometry/PLYReader/index.d.ts [hunk 2]
```diff
@@ -13,7 +13,17 @@ interface IPLYReaderOptions {
...
+   */
+  duplicatePointsForFaceTexture?: boolean;
+
+  /**
+   * The tolerance used to determine if two points are the same.
```
Comment (finetjul) [inline Sources/IO/Geometry/PLYReader/index.d.ts:23]: Mention the default value

**Review by finetjul — COMMENTED** [review]
LGTM

(It would be a plus (not mandatory) if the code could be split in separate functions)

Having a test would great to add a test.

**Comment by daker** [comment]
> LGTM
> 
> (It would be a plus (not mandatory) if the code could be split in separate functions)
> 
> Having a test would great to add a test.
You mean split the postProcess function ? for the test i will try to see what is for other readers

**Comment by finetjul** [comment]
> You mean split the postProcess function ?

I did not realized the code was in `postProcess()`, I guess it is sufficiently separated from the "parser" code, so it's fine to leave it as is.

> for the test i will try to see what is done for other readers

You can look at the OBJReader that has a test.

**Review by finetjul — APPROVED** [review]
LGTM

**Comment by daker** [comment]
@floryst mind merging the PR if it's ok for you ?

**Comment by daker** [comment]
@floryst 
image
