### PR TITLE
fix(type): fix type returned when inserting a point

### LINKED ISSUE #3048: [Bug] Incorrect interface for `insertNextPoint` on `vtkPoints`
### Bug description

The `insertNextPoint` calls the parent class `insertNextTuple` method which returns the idx of the inserted point.

### Steps to reproduce

```javascript
import vtkPoints from "@kitware/vtk.js/Common/Core/Points";

const points = vtkPoints.newInstance();
const idx = points.insertNextPoint(1, 2, 3)  // idx exists but warns void function return value is used
```

### Detailed Behavior

_No response_

### Expected Behavior

Should not warn about returned idx

### Environment

- vtk.js version: latest
- Browsers: chrome
- OS: MacOS

### PR DESCRIPTION
**Pull request by ramonemiliani93**
Fix #3048

### Context
Fixes the interface of the `insertNextPoint` method on the  `vtkPoints` class.

### Results
Updates the interface on the `Points.d.ts` file.

### Changes
- [X] Documentation and TypeScript definitions were updated to match those changes

### PR and Code Checklist

- [X] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [X] Run `npm run reformat` to have correctly formatted code

### Testing

- [ ] This change adds or fixes unit tests 
- [ ] Tested environment:
  - **vtk.js**: 
  - **OS**: 
  - **Browser**:

### CODE REVIEW

File: Sources/Common/Core/Points/index.d.ts [hunk 1]
```diff
@@ -73,8 +73,9 @@ export interface vtkPoints extends vtkDataArray {
 	 * @param {Number} x The x coordinate.
 	 * @param {Number} y The y coordinate.
 	 * @param {Number} z The z coordinate.
+   * @returns {Number} Index of the inserted point.
```
Comment (finetjul) [inline Sources/Common/Core/Points/index.d.ts:76]: please fix the indent

**Review by finetjul — CHANGES_REQUESTED** [review]

**Review by finetjul — APPROVED** [review]
LGTM. Thanks !

**Review by daker — APPROVED** [review]
LGTM
