### PR TITLE
fix(GLTFImporter): fix GLTF Draco normals

### LINKED ISSUE #3192: [Bug] GLTF Draco wrong normals
### Bug description

Wrong Normals with Draco format

https://github.com/user-attachments/assets/782ae8de-6d7e-489d-a892-8eb6483e233b

### Steps to reproduce

Open https://kitware.github.io/vtk-js/examples/GLTFImporter/index.html?model=CesiumMan&flavor=glTF-Draco&scene=0&viewAPI=WebGPU

### Detailed Behavior

_No response_

### Expected Behavior

Draco format renders correctly.

### Environment

- vtk.js version:
- Browsers:
- OS:

### PR DESCRIPTION
**Pull request by daker**
### Context

fix #3192

### Results

https://github.com/user-attachments/assets/742a0bfd-aae1-4aee-b2bc-92ebb4312eef

### Changes
- [x] Documentation and TypeScript definitions were updated to match those changes

### PR and Code Checklist
- [x] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [x] Run `npm run reformat` to have correctly formatted code

### Testing

- [ ] This change adds or fixes unit tests 
- [ ] Tested environment:
  - **vtk.js**: 
  - **OS**: 
  - **Browser**:

### CODE REVIEW

File: Sources/IO/Geometry/GLTFImporter/Extensions.js [hunk 1]
```diff
@@ -89,7 +90,10 @@ export function handleKHRLightsPunctual(extension, transformMatrix, model) {
 export async function handleKHRDracoMeshCompression(extension) {
   const reader = vtkDracoReader.newInstance();
   reader.parse(extension.bufferView);
-  return reader.getOutputData();
+  const pdn = vtkPolyDataNormals.newInstance();
```
Comment (finetjul) [inline Sources/IO/Geometry/GLTFImporter/Extensions.js:93]: shouldn't you NOT compute polydatanormals if the file already contains normals ?

Comment (daker) [reply Sources/IO/Geometry/GLTFImporter/Extensions.js:93]: Yes, i saw that the vtkDracoReader is already setting the normals but i am not sure why the result is not correct, i will see if i can find why

Comment (daker) [reply Sources/IO/Geometry/GLTFImporter/Extensions.js:93]: If i disable the [setNormals ](https://github.com/Kitware/vtk-js/blob/89758edd084dc59dd85908afc2e49ba9d1dc4230/Sources/IO/Geometry/DracoReader/index.js#L174) in vtkDracoReader the rendering is the expected one and the normals array from GLTF and GLTF-Draco are the same size but not same values

Comment (finetjul) [reply Sources/IO/Geometry/GLTFImporter/Extensions.js:93]: You might want to use the GlyphMapper to visualize the normals created by Draco. Maybe that would give a clue about what is wrong...

**Comment by daker** [comment]
@finetjul I have upgraded the draco lib to the latest version and i generate the normals if they are missing.

**Review by finetjul — APPROVED** [review]
LGTM.
@floryst could it be considered as breaking change ?

**Comment by daker** [comment]
@finetjul the only breaking change is the switch to promise/async setDracoDecoder imposed by the library.

**Review by floryst — APPROVED** [review]
I'm good to keep this as a non-breaking change. I'm partly making this call due to draco3d not designating it as a breaking change (assuming they follow semantic versioning), as they introduce it in the 1.3.6->1.4.0 release.
