### PR TITLE
fix(WebGPU): Handle edge visibility for both triangles and triangle strips

### LINKED ISSUE #3125: [Bug] WebGPU not support strips render
### Bug description

I have an .vtp file, I want to render it with geometryViewer example. In WebGL, it render correct. But if I switch to WebGPU renderer, I can't render correct.

Here is my .vtp file. 
[tube.vtp.zip](https://github.com/user-attachments/files/17146729/tube.vtp.zip)

[GeometryViewer WebGL version online example link](https://kitware.github.io/vtk-js/examples/GeometryViewer/index.html)

[GeometryViewer WebGPU version online example link](https://kitware.github.io/vtk-js/examples/GeometryViewer/index.html?viewAPI=WebGPU)

### Steps to reproduce

Open online example link, unzip tupe.vtp.zip file and drop tupe.vtp file to page.

### Detailed Behavior

_No response_

### Expected Behavior

WebGPU version should support strips too.

### Environment

- vtk.js version: latest
- Browsers: Chrome
- OS: MacOS

### PR DESCRIPTION
**Pull request by daker**
### Context

fixes #3125

### Results

image

### Changes

- [ ] Documentation and TypeScript definitions were updated to match those changes

### PR and Code Checklist

- [x] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [x] Run `npm run reformat` to have correctly formatted code

### Testing

- [ ] This change adds or fixes unit tests 
- [ ] Tested environment:
  - **vtk.js**: 
  - **OS**: 
  - **Browser**:

### CODE REVIEW

File: Sources/Rendering/WebGPU/PolyDataMapper/index.js [hunk 1]
```diff
@@ -70,26 +75,40 @@ function vtkWebGPUPolyDataMapper(publicAPI, model) {
...
+        const cellMapper = model.primitives[i];
+        cellMapper.setCellArray(prims[PrimitiveTypes.Triangles]);
+        cellMapper.setCurrentInput(poly);
+        cellMapper.setCellOffset(
+          model.primitives[PrimitiveTypes.Triangles].getCellOffset()
+        );
+        cellMapper.setPrimitiveType(i);
+        cellMapper.setRenderable(model.renderable);
+        cellMappers.push(cellMapper);
+      }
```
Comment (finetjul) [inline Sources/Rendering/WebGPU/PolyDataMapper/index.js:97]:
```
} else {
  model.primitives[PrimitiveTypes.TriangleEdges] = null;
}
```

File: Sources/Rendering/WebGPU/PolyDataMapper/index.js [hunk 2]
```diff
@@ -70,26 +75,40 @@ function vtkWebGPUPolyDataMapper(publicAPI, model) {
...
+        const cellMapper = model.primitives[i];
+        cellMapper.setCellArray(prims[PrimitiveTypes.TriangleStrips]);
+        cellMapper.setCurrentInput(poly);
+        cellMapper.setCellOffset(
+          model.primitives[PrimitiveTypes.TriangleStrips].getCellOffset()
+        );
+        cellMapper.setPrimitiveType(i);
+        cellMapper.setRenderable(model.renderable);
+        cellMappers.push(cellMapper);
       }
```
Comment (finetjul) [inline Sources/Rendering/WebGPU/PolyDataMapper/index.js:116]:
```
} else {
  model.primitives[PrimitiveTypes.TriangleStripEdges] = null;
}
```

File: Sources/Rendering/WebGPU/PolyDataMapper/index.js (hunk 1 above)
Comment (daker) [reply Sources/Rendering/WebGPU/PolyDataMapper/index.js:97]: Thanks, it's fixed

**Review by finetjul — APPROVED** [review]
LGTM
