### PR TITLE
fix(WebGPU): optimize vtkTexture.generateMipmaps

### LINKED ISSUE #3260: [Perf] WebGPU: slow `vtkTexture.generateMipmaps()`
### High-level description

`vtkTexture.generateMipmaps()` takes almost 4sec

### Steps to reproduce

Open https://kitware.github.io/vtk-js/examples/GLTFImporter/index.html?model=DamagedHelmet&viewAPI=WebGPU

### Detailed Current Behavior

Image

### Environment

- vtk.js version: latest
- Browsers: Chrome 137.0.7151.56
- OS: Windows 11

### PR DESCRIPTION
**Pull request by daker**
### Context

This commit generates mipmaps for a given GPU texture using a compute shader.

fixes #3260

### Results

| Before | After |
| -------- | ------- |
| old-generateMipmaps | new-generateMipmaps |

https://github.com/user-attachments/assets/95f65b1f-bf02-4a46-8ba2-0d90aa2fef47

### Changes

- [x] Documentation and TypeScript definitions were updated to match those changes

### PR and Code Checklist

- [x] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [x] Run `npm run reformat` to have correctly formatted code

### Testing

- [ ] This change adds or fixes unit tests 
- [x] Tested environment:
  - **vtk.js**: 
  - **OS**: 
  - **Browser**:

### CODE REVIEW

**Comment by daker** [comment]
At some point `generateMipmaps` needs to be done using the GPU.

File: Sources/Rendering/WebGPU/Texture/index.js [hunk 1]
```diff
@@ -88,48 +88,51 @@ function vtkWebGPUTexture(publicAPI, model) {
...
+            outArray[outOffset + i] = HalfFloat.toHalf(arr[inOffset + i]);
           }
         }
-        return [outArray, outWidthInBytes];
+      } else {
+        for (let v = 0; v < totalRows; v++) {
+          outArray.set(
+            arr.subarray(v * inWidth, (v + 1) * inWidth),
+            v * outWidth
+          );
```
Comment (finetjul) [inline Sources/Rendering/WebGPU/Texture/index.js:131]: could be optimized if outWidth == inWidth

**Review by finetjul — COMMENTED** [review]
having a test would make sure there won't be any regression in the future...

**Comment by daker** [comment]
@finetjul i will try to write some tests

**Comment by daker** [comment]
i moved the `generateMipmaps` to the GPU, displaying the model takes less than 1sec

image

**Comment by daker** [comment]
@finetjul I am not sure it's possible to write a functional test for the webgpu shader

**Comment by daker** [comment]
anyone to review this PR ?

**Comment by jourdain** [comment]
@sankhesh @jspanchu

**Comment by daker** [comment]
I’d appreciate it if someone could take a look. I have some additional optimizations on hold that will further speed up the rendering.

**Review by sankhesh — APPROVED** [review]
LGTM 👍

**Comment by daker** [comment]
@floryst mind merging if you are ok with the changes ?
